// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AuthTokens struct {
	Access  string `json:"access"`
	Refresh string `json:"refresh"`
}

type NewCampaignNode struct {
	Title string `json:"title"`
}

type NewUserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

type TransitionType string

const (
	TransitionTypeClue         TransitionType = "Clue"
	TransitionTypeTemporal     TransitionType = "Temporal"
	TransitionTypeGeographic   TransitionType = "Geographic"
	TransitionTypeRandomly     TransitionType = "Randomly"
	TransitionTypeProactively  TransitionType = "Proactively"
	TransitionTypeHybrid       TransitionType = "Hybrid"
	TransitionTypePlayerDriven TransitionType = "PlayerDriven"
)

var AllTransitionType = []TransitionType{
	TransitionTypeClue,
	TransitionTypeTemporal,
	TransitionTypeGeographic,
	TransitionTypeRandomly,
	TransitionTypeProactively,
	TransitionTypeHybrid,
	TransitionTypePlayerDriven,
}

func (e TransitionType) IsValid() bool {
	switch e {
	case TransitionTypeClue, TransitionTypeTemporal, TransitionTypeGeographic, TransitionTypeRandomly, TransitionTypeProactively, TransitionTypeHybrid, TransitionTypePlayerDriven:
		return true
	}
	return false
}

func (e TransitionType) String() string {
	return string(e)
}

func (e *TransitionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransitionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransitionType", str)
	}
	return nil
}

func (e TransitionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
